config/routes.rb
Rails.application.routes.draw do

  # Users
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }

  # User Profiles
  resources :profiles, only: %i[show new create edit update destroy] do
    resources :reviews, only: %i[new create]
  end

  # Products
  resources :products
  # Product Categories
  get '/categories/comic-books-and-graphic-novels', to: 'products#books', as: 'product_books'
  get '/categories/toys-and-collectibles', to: 'products#toys', as: 'product_toys'
  get '/categories/costumes', to: 'products#costumes', as: 'product_costumes'
  get '/categories/clothing-and-apparel', to: 'products#apparel', as: 'product_apparel'
  # Product Photos
  resources :photos
  # Product Search
  resources :search, only: %i[index]

  # Shopping Cart
  resources :shopping_carts, only: %i[index create destroy]
  # Watchlist
  resources :watchlists, only: %i[index create destroy]
  # Orders
  resources :orders, only: %i[index new create]

  # Messages
  resources :conversations, only: %i[index create show destroy]
  resources :messages, only: %i[update]

  # Contact Support
  resources :contact_support, only: %i[new create]

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                  :integer          not null, primary key
#  user_id             :integer
#  first_name          :string
#  last_name           :string
#  image_data          :string
#  date_of_birth       :date
#  short_bio           :text
#  superpowers         :string
#  favourites          :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  billing_address_id  :integer
#  shipping_address_id :integer
#

class Profile < ApplicationRecord
  include ImageUploader[:image]

  belongs_to :user
  belongs_to :billing_address, class_name: 'Address', foreign_key: 'billing_address_id', dependent: :destroy
  belongs_to :shipping_address, class_name: 'Address', foreign_key: 'shipping_address_id', dependent: :destroy
  accepts_nested_attributes_for :billing_address
  accepts_nested_attributes_for :shipping_address

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_address, presence: true

  # Get Full Name
  def full_name
    full_name = []
    full_name << first_name unless first_name.blank?
    full_name << last_name unless last_name.blank?
    full_name.join(' ').strip
  end

  # Select Australia as Default Country Code
  def selected_country_code(address)
    address.country_code.blank? ? 'AU' : address.country_code
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: %i[show edit update destroy]
  before_action :set_checkbox_same_address, only: %i[show new edit]
  before_action :set_shipping_address, only: %i[create update]

  # GET /profiles
  # GET /profiles.json``
  # def index
  #   @profiles = Profile.all
  # end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    # Order History
    @order_history = @profile.user.orders_descending
    # Customer Reviews
    @customer_reviews = @profile.user.customer_reviews
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @profile.billing_address = Address.new
    @profile.shipping_address = Address.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    # Assign current user to the new profile
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
      authorize @profile
    rescue Pundit::NotAuthorizedError => e
      render :unauthorized
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :first_name, :last_name, :image,
                                      :date_of_birth, :short_bio, :superpowers, :favourites,
                                      billing_address_attributes:
                                      %i[id house_number street_name town_suburb city state postal_code country_code],
                                      shipping_address_attributes:
                                      %i[id house_number street_name town_suburb city state postal_code country_code])
    end

    # Set the checkbox value to true if shipping address is same with billing address
    def set_checkbox_same_address
      return false if @profile.nil?
      @use_same_address = (@profile.shipping_address.attributes.except('id','created_at','updated_at') == @profile.billing_address.attributes.except('id','created_at','updated_at'))
    end

    # If the same address checbox is ticked, copy billing address attributes to shipping address attributes
    def set_shipping_address
      if params[:use_same_address] == '1'
        params[:profile][:shipping_address_attributes][:house_number] = params[:profile][:billing_address_attributes][:house_number]
        params[:profile][:shipping_address_attributes][:street_name] = params[:profile][:billing_address_attributes][:street_name]
        params[:profile][:shipping_address_attributes][:town_suburb] = params[:profile][:billing_address_attributes][:town_suburb]
        params[:profile][:shipping_address_attributes][:city] = params[:profile][:billing_address_attributes][:city]
        params[:profile][:shipping_address_attributes][:state] = params[:profile][:billing_address_attributes][:state]
        params[:profile][:shipping_address_attributes][:postal_code] = params[:profile][:billing_address_attributes][:postal_code]
        params[:profile][:shipping_address_attributes][:country_code] = params[:profile][:billing_address_attributes][:country_code]
      end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def direct_message_topic_between(user1, user2)
    if user1.id < user2.id
      "Conversation between user #{user1.id} and user #{user2.id}"
    elsif user1.id > user2.id
      "Conversation between user #{user2.id} and user #{user1.id}"
    else
      "Conversation with self #{user1.id}"
    end
  end

  def conversation_title_between(user1, user2)
    if user1.id < user2.id
      "Conversation between #{user1.profile.first_name} and #{user2.profile.first_name}"
    elsif user1.id > user2.id
      "Conversation between #{user2.profile.first_name} and #{user1.profile.first_name}"
    else
      "Conversation with self"
    end
  end
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
    <% profile.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :profile_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :profile_last_name %>
  </div>

  <% if profile.image.present? %>
  <div class="photos d-flex justify-content-center">
    <div class="photo" style="<%= style_for_backgound_image(profile.image_url(:thumb)) %>">
    </div>
  </div>
  <% end %>

  <div class="field">
    <%= form.label 'Profile Photo' %>
    <%= form.file_field :image, id: :profile_image %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %><br>
    <%= form.date_select :date_of_birth, id: :profile_date_of_birth, start_year: 1900 %>
  </div>

  <div class="field">
    <%= form.label :short_bio %>
    <%= form.text_area :short_bio, id: :profile_short_bio %>
  </div>

  <div class="field">
    <%= form.label :superpowers, 'If you had superpowers, they are...' %>
    <%= form.text_field :superpowers, id: :profile_superpowers %>
  </div>

  <div class="field">
    <%= form.label :favourites, 'Favourite comic characters' %>
    <%= form.text_field :favourites, id: :profile_favourites %>
  </div>

  <h2>Billing Address</h2>
  <%= form.fields_for :billing_address do |billing_address_form| %>

    <div class="field">
      <%= billing_address_form.label :house_number %>
      <%= billing_address_form.text_field :house_number %>
    </div>

    <div class="field">
      <%= billing_address_form.label :street_name %>
      <%= billing_address_form.text_field :street_name %>
    </div>

    <div class="field">
      <%= billing_address_form.label :town_suburb, 'Town/Suburb' %>
      <%= billing_address_form.text_field :town_suburb %>
    </div>

    <div class="field">
      <%= billing_address_form.label :city %>
      <%= billing_address_form.text_field :city %>
    </div>

    <div class="field">
      <%= billing_address_form.label :state %>
      <%= billing_address_form.text_field :state %>
    </div>

    <div class="field">
      <%= billing_address_form.label :postal_code %>
      <%= billing_address_form.text_field :postal_code %>
    </div>

    <div class="field">
      <%= billing_address_form.label :country_code %>
      <%= billing_address_form.country_select :country_code, selected: profile.selected_country_code(profile.billing_address) %>
    </div>
  <% end %>

  <h2>Shipping Address</h2>
  <%= form.fields_for :shipping_address do |shipping_address_form| %>

    <div class="field">
      <%= check_box_tag :use_same_address, '1', @use_same_address, onclick: "toggle('.field-shipping', this)", class: 'field-shipping-checkbox' %> Use same address as billing address
    </div>

    <div class="field field-shipping">
      <%= shipping_address_form.label :house_number %>
      <%= shipping_address_form.text_field :house_number %>
    </div>

    <div class="field field-shipping">
      <%= shipping_address_form.label :street_name %>
      <%= shipping_address_form.text_field :street_name %>
    </div>

    <div class="field field-shipping">
      <%= shipping_address_form.label :town_suburb, 'Town/Suburb' %>
      <%= shipping_address_form.text_field :town_suburb %>
    </div>

    <div class="field field-shipping">
      <%= shipping_address_form.label :city %>
      <%= shipping_address_form.text_field :city %>
    </div>

    <div class="field field-shipping">
      <%= shipping_address_form.label :state %>
      <%= shipping_address_form.text_field :state %>
    </div>

    <div class="field field-shipping">
      <%= shipping_address_form.label :postal_code %>
      <%= shipping_address_form.text_field :postal_code %>
    </div>

    <div class="field field-shipping">
      <%= shipping_address_form.label :country_code %>
      <%= shipping_address_form.country_select :country_code, selected: profile.selected_country_code(profile.shipping_address) %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  function toggle(className, obj) {
    var $input = $(obj);
    if ($input.is(':checked')) $(className).hide();
    else $(className).show();
  }

  $( document ).ready(function() {
    var $input = $('.field-shipping-checkbox');
    var className = '.field-shipping'
    if ($input.is(':checked')) $(className).hide();
    else $(className).show();
  });
</script>

app/views/profiles/edit.html.erb
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / Edit Profile
</section>
<section class="application profile-form">
  <h2>Editing Profile</h2>

  <%= render 'form', profile: @profile %>
</section>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Image data</th>
      <th>Date of birth</th>
      <th>Short bio</th>
      <th>Superpowers</th>
      <th>Favourites</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= image_tag profile.image_url(:thumb) unless profile.image.nil? %></td>
        <td><%= profile.date_of_birth %></td>
        <td><%= profile.short_bio %></td>
        <td><%= profile.superpowers %></td>
        <td><%= profile.favourites %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / New Profile
</section>
<section class="application profile-form">
  <h2>New Profile</h2>

  <%= render 'form', profile: @profile %>
</section>

app/views/profiles/show.html.erb
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / Profiles / <%= @profile.full_name %>
</section>

<section class="profile-divider row">
  <section class="application profile col col-md-6">
    <h2><%= @profile.full_name %></h2>
    <div class="profile-data1 d-flex flex-column justify-content-center align-items-center">
      <div class="profile-image p-2" style="<%= style_for_backgound_image(@profile.image_url(:thumb)) unless @profile.image.nil? %>"></div>
      <div class="profile-bio p-2"><p><%= @profile.short_bio %></p></div>
    </div>
    <% if current_user.profile == @profile %>
      <div class="profile-info">
        <% if current_user.profile.date_of_birth == Time.now.localtime.to_date %>
          <h3>Happy Birthday</h3>
        <% else %>
          <h3>Birthday</h3>
        <% end %>
        <p><%= @profile.date_of_birth.to_formatted_s(:long_ordinal) %></p>
      </div>
    <% else %>
    
      <div class="profile-info">
        <% if @profile.date_of_birth == Time.now.localtime.to_date %>
          <h3>It's <%= @profile.first_name.possessive %> Birthday</h3>
        <% else %>
          <h3>Birthday</h3>
        <% end %>
        <p><%= @profile.date_of_birth.strftime("%B #{@profile.date_of_birth.day.ordinalize}") %></p>
      </div>
    <% end %>
    <div class="profile-info">
      <h3>Superpowers</h3>
      <p><%= @profile.superpowers %></p>
    </div>
    <div class="profile-info">
      <h3>Favourites</h3>
      <p><%= @profile.favourites %></p>
    </div>
    <div class="profile-info">
      <h3>Neighbourhood</h3>
      <p><%= @profile.billing_address.public_address %></p>
    </div>
    <% if current_user.profile == @profile %>
      <div class="profile-info">
        <h3>Billing Address</h3>
        <p><%= @profile.billing_address.full_address %></p>
      </div>
      <div class="profile-info">
        <h3>Shipping Address</h3>
        <p><%= @profile.shipping_address.full_address %></p>
      </div>
    <% end %>
    <div class="spacer20"></div>
    <div class="profile-buttons d-flex justify-content-end">
      <% if current_user.profile == @profile %>
        <%= link_to button_tag('Edit Profile'), edit_profile_path(@profile), class: 'p-2' %>
        <%= link_to button_tag('Change Password'), edit_user_registration_path, class: 'p-2' %>
      <% else %>
        <!-- Message User about product button -->
        <% if user_signed_in? %>
          <%= form_with(url: conversations_url, local:true, class: 'p-2') do |f| %>
            <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
            <%= f.hidden_field :topic, value: direct_message_topic_between(@profile.user, current_user) %>
            <%= f.hidden_field :title, value: conversation_title_between(@profile.user, current_user) %>
            <%= hidden_field_tag :receiver, @profile.user.id %>
            <%= f.submit 'Message' %>
          <% end %>
        <% end %>

        <!-- Writw a review -->
        <%= link_to button_tag('Write a Review'), new_profile_review_path(@profile), class: 'p-2' %>
      <% end %>
    </div>
  </section>

  <section class="application profile-products col col-md-6">
    <h2>
      <% if current_user.profile == @profile %>
        Products you are selling
      <% else %>
        <%= @profile.first_name.possessive %> products
      <% end %>
    </h2>
    <div class="shopping-cart-list">
      <% unless @profile.user.products_selling.blank? %>
        <% @profile.user.products_selling.each do |store_item| %>
          <div class="cart-item row">
            <div class="cart-left col d-flex flex-wrap">
              <a href="<%= product_path(store_item) %>" class="p-2">
                <div class="cart-item-photo p-2" style="<%= style_for_backgound_image(store_item.photos.first.image_url(:thumb)) unless store_item.photos.blank? %>"></div>
              </a>
              <div class="cart-details align-self-center">
                <p>
                  <span class="cart-item-name"><%= link_to store_item.name, product_path(store_item) %></span><br>
                  <span class="cart-item-condition"><%= store_item.condition %></span><br>
                  <span class="cart-item-weight"><%= pluralize format_grams_to_kg(store_item.weight), 'kg' %></span>
                </p>
              </div>
            </div>
            <div class="cart-right col align-self-center">
              <div class="cart-price">
                <h4><%= number_to_currency store_item.price %></h4>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</section>

<section class="profile-divider row">
  <section class="application profile-customer-reviews col col-md-6">
    <h2>Customer Reviews</h2>
    <% @customer_reviews.each do |review| %>
    <div class="customer-review d-flex">
        <div class="customer-review-stars p-2">
          <%= star_rating(review.rating) %>
        </div>
        <div class="customer-review-summary p-2"><%= summary_rating(review.rating) %></div>
    </div>
    <div class="posted-by-customer">by <%= review.buyer.profile.full_name %> on <%= format_date_to_localtime(review.created_at) %></div>
    <div class="customer-review-comment"><%= review.comment %></div>
    <% end %>
  </section>

  <section class="application profile-products order-history col col-md-6">
    <h2>Order History</h2>
    
    <% @order_history.each do |order| %>
      <% unless order.order_items.blank? %>
        <div class="order-history-list">
          <%= format_date_to_localtime(order.created_at) %>  
          <% order.order_items.each do |order_item| %>
            <div class="cart-item row">
              <div class="cart-left col d-flex flex-wrap">
                <a href="<%= product_path(order_item.product) %>" class="p-2">
                  <div class="cart-item-photo p-2" style="<%= style_for_backgound_image(order_item.product.photos.first.image_url(:thumb)) unless order_item.product.photos.blank? %>"></div>
                </a>
                <div class="cart-details align-self-center">
                  <p>
                    <span class="cart-item-name"><%= link_to order_item.product.name, product_path(order_item.product) %></span><br>
                    <span class="cart-item-condition"><%= order_item.product.condition %></span><br>
                    <span class="cart-item-weight"><%= pluralize format_grams_to_kg(order_item.product.weight), 'kg' %></span>
                  </p>
                </div>
              </div>
              <div class="cart-right col align-self-center">
                <div class="cart-price">
                  <h4><%= number_to_currency order_item.product.price %></h4>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      
    <% end %>
    
  </section>
</section>

<%#= link_to 'Order History', orders_path, class: 'nav-link' %>
<%#= link_to 'Contact Support', new_contact_support_path, class: 'nav-link' %>

app/views/profiles/unauthorized.html.erb
<% document = 'Profile' %>
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / Unauthorized
</section>

<section class="unauthorized text-center">
  <h2>
    You are not authorized to modify this <%= document %>
  </h2>
</section>