config/routes.rb
Rails.application.routes.draw do

  # Users
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }

  # User Profiles
  resources :profiles, only: %i[show new create edit update destroy] do
    resources :reviews, only: %i[new create]
  end

  # Products
  resources :products
  # Product Categories
  get '/categories/comic-books-and-graphic-novels', to: 'products#books', as: 'product_books'
  get '/categories/toys-and-collectibles', to: 'products#toys', as: 'product_toys'
  get '/categories/costumes', to: 'products#costumes', as: 'product_costumes'
  get '/categories/clothing-and-apparel', to: 'products#apparel', as: 'product_apparel'
  # Product Photos
  resources :photos
  # Product Search
  resources :search, only: %i[index]

  # Shopping Cart
  resources :shopping_carts, only: %i[index create destroy]
  # Watchlist
  resources :watchlists, only: %i[index create destroy]
  # Orders
  resources :orders, only: %i[index new create]

  # Messages
  resources :conversations, only: %i[index create show destroy]
  resources :messages, only: %i[update]

  # Contact Support
  resources :contact_support, only: %i[new create]

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  id         :integer          not null, primary key
#  buyer_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ShoppingCart < ApplicationRecord
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id'
  has_many :shopping_cart_items
  has_many :products, through: :shopping_cart_items, dependent: :destroy

  # Add product to shopping cart
  def add_product(product)
    products << product
    # save
  end

  # Remove product from shopping cart
  def remove_product(product)
    products.delete(product)
    # save
  end

  # Access a product from cart
  def product(product)
    products.find(product.id)
  end

  # Check if product already added in cart
  def includes_product?(product)
    products.include?(product)
  end

  # Get total price of products in cart (in cents)
  def products_total_price
    (products.sum(:price) * 100).to_i
  end

  # Get total price of postage (in cents)
  def postage_total_price
    total = 0.0
    products.where(postage: 'By Weight').group(:seller_id).sum(:weight).each_value do |weight|
      total += (weight <= 500 ? 4.0 : 6.0)
    end
    (total * 100).to_i
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile!
  # before_action :set_shopping_cart, only: [:show, :destroy]
  # protect_from_forgery

  # GET /shopping_carts
  # GET /shopping_carts.json
  def index
    # Get shopping cart items
    @shopping_cart = current_user.shopping_cart if !current_user.shopping_cart.blank?

    if @shopping_cart.blank?
      # Set prices to 0
      @postage_total_price = 0.0
      @postage_total_price = 0.0
    else
      # Get products total price
      @postage_total_price = @shopping_cart.products_total_price

      # Get total postage price
      @postage_total_price = @shopping_cart.postage_total_price
    end

    # Prepare the Order for Checkout
    @order = Order.new
  end

  # POST /shopping_carts
  # POST /shopping_carts.json
  def create
    # Get the product id
    shopping_cart_item = params.require(:shopping_cart)[:product_id]
    # Find the product id
    product = Product.find(shopping_cart_item)
    # Find the shopping cart
    @shopping_cart = current_user.shopping_cart unless current_user.shopping_cart.blank?
    if current_user.shopping_cart.blank?
      @shopping_cart = ShoppingCart.new(buyer: current_user)
    end
    # Add product to shopping cart
    @shopping_cart.add_product(product)
    # Change product status to Reserved
    product.change_status_to('Reserved')

    redirect_to shopping_carts_url
  end

  # DELETE /shopping_carts/1
  # DELETE /shopping_carts/1.json
  def destroy
    # Get the product id
    shopping_cart_item = params.permit(:id)[:id]
    # Find the product id
    product = Product.find(shopping_cart_item)
    # Delete product id from shopping_cart
    current_user.shopping_cart.remove_product(product)
    # Set product status to Available
    product.change_status_to('Available')

    redirect_to shopping_carts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart
      @shopping_cart = ShoppingCart.find(params[:id])
    end

end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart, local: true) do |form| %>
  <% if shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
      <% shopping_cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :shopping_cart_user_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :shopping_cart_product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_carts/edit.html.erb
<h1>Editing Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Show', @shopping_cart %> |
<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/index.html.erb
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / Shopping Cart
</section>

<section class="application shopping-cart">
  <% if @shopping_cart.blank? || @shopping_cart.products.blank? %>
  <h2>Your Shopping Cart is empty</h2>
  <% else %>
    <h2>Shopping Cart</h2>
    <div class="shopping-cart-list">
      <% unless @shopping_cart.blank? %>
        <% @shopping_cart.products.each do |shopping_cart_item| %>
          <div class="cart-item row">
            <div class="cart-left col d-flex flex-wrap">
              <a href="<%= product_path(shopping_cart_item) %>" class="p-2">
                <div class="cart-item-photo p-2" style="<%= style_for_backgound_image(shopping_cart_item.photos.first.image_url(:thumb)) unless shopping_cart_item.photos.blank? %>"></div>
              </a>
              <div class="cart-details align-self-center">
                <p>
                  <span class="cart-item-name"><%= link_to shopping_cart_item.name, product_path(shopping_cart_item) %></span><br>
                  <span class="cart-item-condition"><%= shopping_cart_item.condition %></span><br>
                  <span class="cart-item-weight"><%= pluralize format_grams_to_kg(shopping_cart_item.weight), 'kg' %></span><br>
                  <span class="cart-item-weight">Postage: <%= shopping_cart_item.postage %></span>
                </p>
              </div>
            </div>
            <div class="cart-right col align-self-center">
              <div class="cart-price">
                <h4><%= number_to_currency  shopping_cart_item.price %></h4>
              </div>
              <div class="spacer10"></div>
              <div class="cart-remove">
                  <%= link_to 'Remove from Cart', shopping_cart_path(shopping_cart_item), method: :delete %>
              </div>
            </div>
          </div>
          
        <% end %>
      <% end %>
    </div>
    <div class="spacer10"></div>
    <div class="shopping-cart-totals">
      <div class="shopping-cart-prices">
        <% unless @shopping_cart.blank? %>
        <h6>Product Price: <%= number_to_currency format_amount_from_cents(@shopping_cart.products_total_price) %></h6>
        <h6>Postage Price: <%= number_to_currency  format_amount_from_cents(@shopping_cart.postage_total_price) %></h6>
        <div class="spacer10"></div>
        <h3>Total: <%= number_to_currency format_amount_from_cents(@shopping_cart.products_total_price + @shopping_cart.postage_total_price) %></h3>
        <% end %>
      </div>
      <div class="spacer20"></div>
      <div class="proceed-to-checkout">
        <%= link_to button_tag('Proceed to Checkout'), new_order_path unless @shopping_cart.blank? %>
      </div>
    </div>
    <div class="spacer20"></div>
    <div><em>Postage price is calculated per seller<br>
      $4 for items between 0g-500g)<br>
      $6 for (over 500g)</em></div>
  <% end %>
</section>

app/views/shopping_carts/new.html.erb
<h1>New Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @shopping_cart.buyer.email %>
</p>

<p>
  <strong>Product:</strong>
  <%= @shopping_cart.product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shopping_cart.product.price %>
</p>

<%= link_to 'Edit', edit_shopping_cart_path(@shopping_cart) %> |
<%= link_to 'Back', shopping_carts_path %>