config/routes.rb
Rails.application.routes.draw do

  # Users
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords' }

  # User Profiles
  resources :profiles, only: %i[show new create edit update destroy] do
    resources :reviews, only: %i[new create]
  end

  # Products
  resources :products
  # Product Categories
  get '/categories/comic-books-and-graphic-novels', to: 'products#books', as: 'product_books'
  get '/categories/toys-and-collectibles', to: 'products#toys', as: 'product_toys'
  get '/categories/costumes', to: 'products#costumes', as: 'product_costumes'
  get '/categories/clothing-and-apparel', to: 'products#apparel', as: 'product_apparel'
  # Product Photos
  resources :photos
  # Product Search
  resources :search, only: %i[index]

  # Shopping Cart
  resources :shopping_carts, only: %i[index create destroy]
  # Watchlist
  resources :watchlists, only: %i[index create destroy]
  # Orders
  resources :orders, only: %i[index new create]

  # Messages
  resources :conversations, only: %i[index create show destroy]
  resources :messages, only: %i[update]

  # Contact Support
  resources :contact_support, only: %i[new create]

  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  seller_id    :integer
#  name         :string
#  price        :decimal(, )
#  description  :text
#  condition    :string
#  status       :string
#  category     :string
#  manufacturer :string
#  publisher    :string
#  publish_date :date
#  author       :string
#  illustrator  :string
#  isbn_10      :string
#  isbn_13      :string
#  dimensions   :string
#  weight       :decimal(, )      default(0.0)
#  keywords     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  postage      :string
#

class Product < ApplicationRecord
  include AlgoliaSearch

  algoliasearch do
    # All Attributes Used by Algolia
    attribute :name, :keywords, :description, :seller_name, :manufacturer, :publisher, :author, :illustrator, :view_count, :latitude, :longitude, :status, :category

    # Search Index
    searchableAttributes ['name', 'keywords', 'unordered(description)', 'seller_name', 'unordered(manufacturer)', 'unordered(publisher)', 'unordered(author)', 'unordered(illustrator)']

    # Rank by Product View Count
    customRanking ['asc(view_count)']

    # Location Search by Radius
    geoloc :latitude, :longitude

    # Filters
    attributesForFaceting [:status, :manufacturer, :publisher, :category, :seller_name]
    # tags [:keywords]
  end

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos
  belongs_to :seller, class_name: 'User'
  has_many :product_views, dependent: :destroy
  has_many :shopping_carts, dependent: :destroy
  has_many :watchlists, dependent: :destroy
  has_many :orders, dependent: :destroy

  enum category_types: ['Comic Books & Graphic Novels', 'Toys & Collectibles', 'Costumes', 'Clothing & Apparel']
  enum condition_types: ['Brand New', 'Mint', 'Good', 'Fair', 'Poor']
  enum status_types: ['Available', 'Reserved', 'Sold']
  enum postage_types: ['None/Pickup Only', 'By Weight']

  validates :name, uniqueness: { scope: :seller_id }
  validates :price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 999999.99 }
  validates :description, presence: true
  validates :condition, presence: true
  validates :status, presence: true
  validates :category, presence: true
  validates :name, presence: true
  validates :postage, presence: true
  validates :weight, numericality: { greater_than_or_equal_to: 0 }
  validates :isbn_10, length: {minimum: 10, maximum: 10}, allow_blank: true
  validates :isbn_13, length: {minimum: 10, maximum: 13}, allow_blank: true
  validates :name, length: {maximum: 50}
  
  # Full name of the Seller
  def seller_name
    seller.profile.full_name
  end

  # Location of the Seller
  def seller_location
    seller.profile.billing_address.public_address
  end

  # Seller's latitude
  def latitude
    seller.profile.billing_address.latitude
  end

  # Seller's longitude
  def longitude
    seller.profile.shipping_address.longitude
  end

  # Distance between the seller and buyer
  def distance_from_seller(buyer)
    seller_coordinates = "#{latitude}, #{longitude}"
    buyer_coordinates = "#{buyer.profile.billing_address.latitude}, #{buyer.profile.billing_address.longitude}"
    Geocoder::Calculations.distance_between(seller_coordinates, buyer_coordinates, :units => :km)
  end

  # When the buyer, views the Product
  def toggle_viewed_by(buyer)
    unless ProductView.find_by(product_id: self.id, buyer: buyer).present?
      ProductView.create(product_id: self.id, buyer: buyer)
    end
  end

  # Count the Product Views
  def view_count
    product_views.count
  end

  # Change status of product to
  def change_status_to(new_status)
    self.status = new_status
    save
  end

  # For development purposes, return all products back to the store
  def self.mass_recall
    ShoppingCart.destroy_all
    Product.update_all(status: 'Available')
  end

  # Query product by Category and Available
  scope :category, ->(category) {
    Product.where(category: category, status: 'Available').order(created_at: :desc)
  }

  # Query list of top products
  scope :top_products, ->(up_to_rank){
    # Find an array of top viewed products sorted in descending order
    array_of_products = Product.where(status: 'Available').left_joins(:product_views).group(:product_id).count(:buyer_id).sort_by{|k,v| v}.reverse.to_h.keys[0,up_to_rank]
    
    # Get these array of Products while preserving sort order of array
    Product.where(id: array_of_products).index_by(&:id).slice(*array_of_products).values
  }
end

app/models/product_view.rb
# == Schema Information
#
# Table name: product_views
#
#  id         :integer          not null, primary key
#  product_id :integer
#  buyer_id   :integer
#

class ProductView < ApplicationRecord
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id'
  belongs_to :product
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_profile!
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_product_containers, only: [:index, :books, :toys, :costumes, :apparel, :top_products]
  # GET /products
  # GET /products.json
  def index
    # @products = Product.all

    # Latest additions - Last 12 new products
    @latest_products = Product.where(status: 'Available').order(created_at: :desc).limit(12)

    # Rcently sold - Last 12 sold products
    @sold_products = Product.where(status: 'Sold').order(updated_at: :desc).limit(12)

    # Top 12 viewed products
    # @top_products = Product.where(status: 'Available').sort_by(&:view_count).reverse[0,12]
    @top_products = Product.top_products(12)

    # Carousel Images
    # @carousel = Photo.limit(5).order("RANDOM()")
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
    # Toggle product view if user has not already viewed the product
    @product.toggle_viewed_by(current_user)

    # Top Customer Review
    @top_customer_reviews = @product.seller.top_customer_reviews

    # Initialise a new shopping cart item
    @shopping_cart = ShoppingCart.new
    # Initialise a new watchlist item
    @watchlist = Watchlist.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.seller = current_user
    @product.status = 'Available'

    respond_to do |format|
      if @product.save
        # Get photos directly from the params and save them to the database one by one
        if params[:product][:images]
          params[:product][:images].each { |image|
            Photo.create(product: @product, image: image)
          }
        end

        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        # Get photos directly from the params and save them to the database one by one
        if params[:product][:images]
          params[:product][:images].each { |image|
            Photo.create(product: @product, image: image)
          }
        end

        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Product category - Comic Books & Graphic Novels
  def books
    @products = Product.category('Comic Books & Graphic Novels')
  end

  # Product category - Toys & Collectibles
  def toys
    @products = Product.category('Toys & Collectibles')
  end

  # Product category - Costumes
  def costumes
    @products = Product.category('Costumes')
  end

  # Product category - Clothing & Apparel
  def apparel
    @products = Product.category('Clothing & Apparel')
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      authorize @product
    rescue Pundit::NotAuthorizedError => e
      render :unauthorized
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:seller_id, :name, :price, :description, :condition, :status, :category, :manufacturer, :publisher, :publish_date, :author, :illustrator, :isbn_10, :isbn_13, :dimensions, :weight, :keywords, :postage)
    end

    # Initialise the shopping cart and watchlist
    def set_product_containers
      # Add to Cart buttons in product listing
      @shopping_cart = ShoppingCart.new
  
      # Add to Watchlist buttons
      @watchlist = Watchlist.new
    end

end

app/helpers/products_helper.rb
module ProductsHelper
  # Conversation Topic for Product Inquiry
  def product_inquiry_topic_about(product, buyer)
    "Inquiry about product #{product.id} between user #{product.seller.id} and user #{buyer.id}"
  end

  # Conversation Title for Product Inquiry
  def conversation_title_about(product, buyer)
    "Inquiry about #{product.name} between #{product.seller.profile.first_name} and #{buyer.profile.first_name}"
  end

  # Check if a product is added to the shopping cart
  def added_to_cart?(product)
    return false unless user_signed_in?
    return false if current_user.shopping_cart.blank?
    current_user.shopping_cart.includes_product?(product)
  end

  # Check if a product is added to the watchlist
  def added_to_watchlist?(product)
    return false unless user_signed_in?
    return false if current_user.watchlist.blank?
    current_user.watchlist.includes_product?(product)
  end

  # Check if a product is already sold
  def sold?(product)
    product.status == 'Sold'
  end

  # Check if a product is already checked out by someone
  def reserved?(product)
    product.status == 'Reserved'
  end

  # Get button text for Add to Cart
  def add_to_cart_text(product)
    reserved?(product) ? 'Reserved' : sold?(product) ? 'Sold' : added_to_cart?(product) ? 'Added to Cart' : 'Add to Cart'
  end

  # Check if Add to Cart button is disabled
  def disable_add_to_cart?(product)
    added_to_cart?(product) || sold?(product) || reserved?(product) || product.seller == current_user
  end
end

app/views/products/_category.html.erb
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / <%= link_to 'Products', products_path %> / <%= html_escape(category) %>
</section>
<section class="products">
  <% if @products.blank? %>
    <h2 class="products-list-label">No <%= html_escape(category) %> available at this time</h2>
  <% else %>
    <h2 class="products-list-label"><%= html_escape(category) %></h2>
    <div class="products-list row justify-content-center justify-content-md-start">
      <%= render @products %>
    </div>
  <% end %>
</section>

app/views/products/_product.html.erb
<div class="col-4 card product-item">
  <a href="<%= product_path(product) %>">
    <div class="card-img-top product-photo" style="<%= style_for_backgound_image(product.photos.first.image_url(:thumb)) unless product.photos.blank? %>"></div>  
  </a>
  <div class="card-body">
    <h4 class="card-title text-center"><%= number_to_currency product.price %></h4>
    <p class="card-text text-center">
      <%= product.name %><br>
    </p>
    <p class="view_count text-center">
      <%= pluralize product.view_count, 'people' %> viewed this
    </p>
    <% if user_signed_in? && product.seller != current_user %>
      <div class="button-cart text-center">
        <!-- Add to cart button -->
        <%= form_with model: @shopping_cart, method: :create, local: true do |f| %>
          <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
          <%= f.hidden_field :product_id, value: product.id %>
          <%= f.submit add_to_cart_text(product), disabled: disable_add_to_cart?(product) %>
        <% end %>
      </div>
      <div class="button-watchlist text-center">
        <!-- Add to watchlist button -->
        <% if added_to_watchlist?(product) %>
          <%= form_with model: current_user.watchlist, method: :delete, local: true do |f| %>
            <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit 'Remove from Watchlist' %>
          <% end %>
        <% else %>
          <%= form_with model: @watchlist, method: :create, local: true do |f| %>
            <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit 'Add to Watchlist' %>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="button-cart text-center">
        <%= link_to button_tag('View'), product %>
      </div>
      <div class="button-watchlist text-center">
        You own this item
      </div>
    <% end %>
  </div>
</div>

app/views/products/apparel.html.erb
<% category = 'Clothing & Apparel' %>
<%= render :partial => 'category', :locals => {:category=>category} %>

app/views/products/books.html.erb
<% category = 'Comic Books & Graphic Novels' %>
<%= render :partial => 'category', :locals => {:category=>category} %>

app/views/products/costumes.html.erb
<% category = 'Costumes' %>
<%= render :partial => 'category', :locals => {:category=>category} %>

app/views/products/edit.html.erb
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / Edit Product
</section>
<section class="application form-product">
  <h2>Edit Product</h2>

  <%= render 'form', product: @product %>
</section>

app/views/products/index.html.erb
<section class="hero">
  <div id="hero-carousel" class="hero-carousel carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active" style="<%= style_for_backgound_image(asset_url('carousel1.jpg')) %>"></div>
      <div class="carousel-item" style="<%= style_for_backgound_image(asset_url('carousel2.jpg')) %>"></div>
      <div class="carousel-item" style="<%= style_for_backgound_image(asset_url('carousel3.jpg')) %>; background-position: top center;"></div>
      <div class="carousel-item" style="<%= style_for_backgound_image(asset_url('carousel4.jpg')) %>; background-position: top center;"></div>
      <div class="carousel-item" style="<%= style_for_backgound_image(asset_url('carousel5.jpg')) %>"></div>
      <div class="carousel-item" style="<%= style_for_backgound_image(asset_url('carousel6.jpg')) %>; background-position: top center;"></div>
    </div>
    <a class="carousel-control-prev" href="#hero-carousel" role="button" data-slide="prev" onclick="$('#hero-carousel').carousel('prev'); return false;">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#hero-carousel" role="button" data-slide="next" onclick="$('#hero-carousel').carousel('next'); return false;">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="new-product-button d-flex flex-wrap justify-content-center">
    <%= link_to button_tag('Sell an Item'), new_product_path, class: 'p-2' %>
    <%= link_to button_tag('Find an Item'), search_index_path, class: 'p-2' %>
  </div>
</section>

<% unless @latest_products.blank? %>
<section class="products">
  <h2 class="products-list-label">Latest Additions</h2>
  <div class="products-list row justify-content-center justify-content-md-start">
    <%= render @latest_products %>
  </div>
</section>
<% end %>

<% unless @top_products.blank? %>
<section class="products">
  <h2 class="products-list-label">Trending Items</h2>
  <div class="products-list row justify-content-center justify-content-md-start">
    <%= render @top_products %>
  </div>
</section>
<% end %>

<% unless @sold_products.blank? %>
<section class="products">
  <h2 class="products-list-label">Recently Sold Items</h2>
  <div class="products-list row justify-content-center justify-content-md-start">
    <%= render @sold_products %>
  </div>
</section>
<% end %>

<script>
  $('.carousel').carousel({
    interval: 2000,
    pause: "false"
  }).carousel('cycle')
</script>

app/views/products/show.html.erb
<section class="breadcrumbs">
  <%= link_to 'Home', root_path %> / <%= @product.category %>
</section>
<section class="product-show">
  <div class="spacer10 product-desktop-only"></div>
  <h2 class="product-title product-mobile-only"><%= @product.name %></h2>
  <div class="seller-divider row product-mobile-only">
    <div class="seller-summary col">
      <div class="posted-by">Posted by <%= link_to @product.seller.profile.full_name, @product.seller.profile %></div>
      <div class="product-condition-and-views"><%= @product.condition %> | <%= pluralize(@product.view_count, 'product view') %></div>
    </div>
    <div class="seller-ratings col align-items-end">
      <div class="ratings-stars"><%= star_rating(@product.seller.average_review_rating) %> <span><%= @product.seller.average_review_rating.round(2) %> out of</span></div>
      <div class="ratings-review"><%= pluralize @product.seller.reviews.count, 'customer review' %></div>
    </div>
  </div>

  <div class="product-divider row">
    <div class="product-photos carousel slide col" id="product-photos" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <% if @product.photos.blank? %>
        <div class="carousel-item active d-flex align-items-center justify-content-center"><span class="p-2">No Photos Available</span></div>
        <% else %>
        <% @product.photos.each_with_index do |photo, index| %>
        <div class="carousel-item <%= 'active' if index==0 %>" style="<%= style_for_backgound_image(photo.image_url(:original)) %>">
          <%#= image_tag photo.image_url(:thumb), height: 200 %>
        </div>
        <% end %>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#product-photos" role="button" data-slide="prev" onclick="$('#product-photos').carousel('prev'); return false;">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#product-photos" role="button" data-slide="next" onclick="$('#product-photos').carousel('next'); return false;">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    
    <div class="product-desktop-only product-desktop-only-margin col">
      <h2 class="product-title"><%= @product.name %></h2>
      <div class="spacer20"></div>
      <div class="seller-divider">
        <div class="seller-summary">
          <div class="posted-by">Posted by <%= link_to @product.seller.profile.full_name, @product.seller.profile %></div>
          <div class="spacer10"></div>
          <div class="product-condition-and-views">Condition: <%= @product.condition %></div>
          <div class="spacer10"></div>
          <div class="product-condition-and-views"><%= pluralize @product.view_count, 'people' %> viewed this product</div>
        </div>
        <div class="spacer20"></div>
        <div class="seller-ratings seller-ratings-align-left">
          <div class="ratings-stars"><%= star_rating(@product.seller.average_review_rating) %></div>
          <div class="spacer10"></div>
          <div class="ratings-review"><span>This seller has a rating of <%= @product.seller.average_review_rating.round(2) %> out of </span><%= pluralize @product.seller.reviews.count, 'customer review' %></div>
        </div>
      </div>
      <div class="spacer20"></div>
      <div class="product-price product-price-align-left">
        <h3><%= number_to_currency @product.price %></h3>
      </div>
      <div class="spacer20"></div>
      <div class="product-buttons d-flex justify-content-center">
        <% if @product.seller == current_user %>
          <% if @product.status != 'Sold' %>
            <%= link_to button_tag('Edit Product'), edit_product_path(@product) %>
            <%= link_to button_tag('Delete Product'), edit_product_path(@product) %>    
          <% end %>
        <% else %>
          <!-- Add to cart button -->
          <%= form_with model: @shopping_cart, method: :create, local: true, class: 'p-2' do |f| %>
            <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
            <%= f.hidden_field :product_id, value: @product.id %>
            <%= f.submit add_to_cart_text(@product), disabled: disable_add_to_cart?(@product) %>
          <% end %>
          <!-- Add to watchlist button -->
          <% if added_to_watchlist?(@product) %>
            <%= form_with model: current_user.watchlist, method: :delete, local: true, class: 'p-2' do |f| %>
              <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.submit 'Remove from Watchlist' %>
            <% end %>
          <% else %>
            <%= form_with model: @watchlist, method: :create, local: true, class: 'p-2' do |f| %>
              <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
              <%= f.hidden_field :product_id, value: @product.id %>
              <%= f.submit 'Add to Watchlist' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="spacer10"></div>
  <div class="product-description">
    <p>
      <%= @product.description %>
    </p>
  </div>

  <div class="spacer10"></div>
  <div class="product-price product-mobile-only">
    <h3><%= number_to_currency @product.price %></h3>
  </div>
  <div class="spacer10"></div>

  <div class="product-buttons d-flex justify-content-end product-mobile-only">
    <% if @product.seller == current_user %>
      <% if @product.status != 'Sold' %>
        <%= link_to button_tag('Edit Product'), edit_product_path(@product) %>
        <%= link_to button_tag('Delete Product'), edit_product_path(@product) %>    
      <% end %>
    <% else %>
      <!-- Add to cart button -->
      <%= form_with model: @shopping_cart, method: :create, local: true, class: 'p-2' do |f| %>
        <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
        <%= f.hidden_field :product_id, value: @product.id %>
        <%= f.submit add_to_cart_text(@product), disabled: disable_add_to_cart?(@product) %>
      <% end %>
      <!-- Add to watchlist button -->
      <% if added_to_watchlist?(@product) %>
        <%= form_with model: current_user.watchlist, method: :delete, local: true, class: 'p-2' do |f| %>
          <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.submit 'Remove from Watchlist' %>
        <% end %>
      <% else %>
        <%= form_with model: @watchlist, method: :create, local: true, class: 'p-2' do |f| %>
          <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.submit 'Add to Watchlist' %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="spacer10"></div>
  <div class="product-details">
    <h2>Product Details</h2>
    <p>
      <%= simple_format('Added on '+format_date_to_localtime(@product.created_at)) unless @product.created_at.blank? %>
      <%= simple_format('Category: '+@product.category) unless @product.category.blank? %>
      <%= simple_format('Author: '+@product.author) unless @product.author.blank? %>
      <%= simple_format('Illustrator: '+@product.illustrator) unless @product.illustrator.blank? %>
      <%= simple_format('ISBN-10: '+@product.isbn_10) unless @product.isbn_10.blank? %>
      <%= simple_format('ISBN-13: '+@product.isbn_13) unless @product.isbn_13.blank? %>
      <%= simple_format('Manufacturer: '+@product.manufacturer) unless @product.manufacturer.blank? %>
      <%= simple_format('Publisher: '+@product.publisher) unless @product.publisher.blank? %>
      <%= simple_format('Published/Manufactured on '+@product.publish_date.to_formatted_s(:long_ordinal)) unless @product.publish_date.blank? %>
      <%= simple_format('Dimensions: '+@product.dimensions) unless @product.dimensions.blank? %>
      <%= simple_format('Weight: '+(pluralize format_grams_to_kg(@product.weight), 'kg')) unless @product.weight.blank? %>
      <%= simple_format('Postage: '+@product.postage) unless @product.postage.blank? %>
    </p>
  </div>
  <div class="spacer10"></div>
</section>

<section class="product-section-divider row">
  <section class="seller-info col col-md-6">
    <h2>About the Seller</h2>
    <div class="seller-divider row">
      <a href="<%= profile_path(@product.seller.profile) %>">
        <div class="seller-photo col" style="<%= style_for_backgound_image(@product.seller.profile.image_url(:thumb)) %>"></div>
      </a>
      <div class="seller-data col">
        <div class="seller-name"><%= link_to @product.seller_name, @product.seller.profile %></div>
        <div class="seller-location"><%= @product.seller_location %></div>
        <div class="seller-description"><%= @product.seller.profile.short_bio %></div>
        <!-- <div class="seller-reviews d-flex justify-content-end">
          <div class="seller-stars p-2"><%#= star_rating(@product.seller.average_review_rating) %></div>
          <div class="seller-review-count p-2">
              <%#= pluralize @product.seller.reviews.count, 'customer review' %><br>
              <%#= @product.seller.average_review_rating.round(2) %> out of 5
          </div>
        </div> -->
      </div>
    </div>
    <% if @product.seller != current_user %>
      <div class="seller-buttons d-flex justify-content-end">
        <!-- Message User about product button -->
        <% if user_signed_in? %>
          <%= form_with(url: conversations_url, local:true, class: 'p-2') do |f| %>
            <%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
            <%= f.hidden_field :topic, value: product_inquiry_topic_about(@product, current_user) %>
            <%= f.hidden_field :title, value: conversation_title_about(@product, current_user) %>
            <%= hidden_field_tag :receiver, @product.seller.id %>
            <%= f.submit 'Message' %>
          <% end %>
        <% end %>

        <!-- Writw a review -->
        <%= link_to button_tag('Write a Review'), new_profile_review_path(@product.seller.profile), class: 'p-2' %>
      </div>
    <% end %>
  </section>

  <section class="top-customer-reviews col col-md-6">
    <h2>Top Customer Reviews</h2>
    <% @top_customer_reviews.each do |review| %>
    <div class="customer-review d-flex">
        <div class="customer-review-stars p-2">
          <%= star_rating(review.rating) %>
        </div>
        <div class="customer-review-summary p-2"><%= summary_rating(review.rating) %></div>
    </div>
    <div class="posted-by-customer">by <%= review.buyer.profile.full_name %> on <%= format_date_to_localtime(review.created_at) %></div>
    <div class="customer-review-comment"><%= review.comment %></div>
    <% end %>
  </section>
</section>

<script>
  $('.carousel').carousel('pause')
</script>